package com.payu.baas.coreUI.util.enums

enum class LastCall {
    NONE,
    USER_STATE,
    KARZA_KEY,
    APPLICATION_ID,
    CARD_DETAILS,
    CARD_IMAGE,
    GET_PIN_STATUS,
    GET_CLIENT_TOKEN,
    GET_SALARY_ADVANCE_INFO,
    SET_LIMITS,
    UN_BLOCK,
    GET_TRANSACTION_MODE,
    SET_TRANSACTION_MODE,
    UPDATE_PIN,
    CARD_SET_PIN,
    GET_TRANSACTION_LIST,
    GET_TRANSACTION_DETAIL
}