@file:JvmSynthetic

package com.payu.baas.coreUI.util

object BaaSConstantsUI {

    // BASE URL
    const val PDF_LOADING_URL = "https://docs.google.com/gview?embedded=true&url="
    const val PREFS_FILE_NAME: String = "baasSdkFile"
    const val PERMISSION_RESULT = "PERMISSION_RESULT"
    const val ACCOUNT_FAILURE_REASON_KEY = "keyAccountFailureReason"

    // Bundle arguments
    const val ARGUMENTS_TITLE = "title"
    const val ARGUMENTS_MOBILE_NUMBER = "mobileNumber"
    const val ARGUMENTS_IMEI = "imei"
    const val ARGUMENTS_ACCOUNT_DETAILS = "accountDetails"
    const val ARGUMENTS_CARD_RE_ORDER = "cardReOrder"
    const val ARGUMENTS_ADDRESS_DETAILS = "addressDetails"

    const val ARGUMENTS_BENEFICIARY_MODEL = "BeneficiaryModel"
    const val ARGUMENTS_IFSC_CODE_DETAIL_MODEL = "IFSCCodeDetailModel"
    const val ARGUMENTS_ALLOW_UNDO_DELETED_BENEFICIARY = "AllowToUndoDeletedBeneficiary"
    const val ARGUMENTS_FROM_MODULE = "FromModule"
    const val ARGUMENTS_TRANSACTION_ID = "TransactionID"
    const val ARGUMENTS_AMOUNT_CHARGED = "AmountCharged"
    const val ARGUMENTS_TRANSACTION_DETAIL_MODEL = "TransactionDetailModel"
    const val ARGUMENTS_ADVANCE_USAGE_HISTORY_MODEL = "advanceUsageHistoryModel"
    const val ARGUMENTS_ADVANCE_MODEL = "advanceModel"

    //Date Formats
    val ddMMyyyy = "dd/MM/yyyy"
    val dd_MM_yyyy = "dd-MM-yyyy"
    val yyyyMMdd = "yyyy-MM-dd"
    val MMMyyyy = "MMM yyyy"
    val ddMMMyyyyhhmma = "dd MMM yyyy hh:mm a"

    // API values
    const val BS_SP_KARZA_USER_SELFIE = "karza_user_selfie"
    const val BS_SP_KARZA_AADHAR_RESPONSE = "karza_aadhar_response"
    const val BS_SP_KARZA_AADHAAR_CONTENT = "karza_aadhaar_content"
    const val BS_SP_KARZA_AADHAAR_CODE = "karza_aadhaar_code"
    const val BS_SP_USER_STATE = "user_state"
    const val REGISTERED_MOBILE_NUMBER = "registered_mobile_number"
    const val USER_MOBILE_NUMBER = "user_mobile_number"
    const val USER_EMPLOYEE_ID = "USER_EMPLOYEE_ID"
    const val USER_NAME = "user_name"
    const val OLD_PASSCODE = "oldPasscode"

    const val MOBILE_NUMBER = "mobile_number"
    const val SECOND_TIME_OTP = "OTP dobara send kr diya hai."

    const val MANUAL_ALLOW_PERMISSIONS = "Go to settings and enable missing permissions."
    const val WITHOUT_PERMISSION =
        "Bina permission diye aap aage nahi bad payenge. Kripya dobara permission dien"
    var PROFILE_SNACKBAR_FLAG_VALUE = "0"
    const val PROFILE_SNACKBAR_FLAG_KEY = "PROFILE_SNACKBAR_FLAG_KEY"

    var EDIT_ADDRESS_SNACKBAR_FLAG_VALUE = "0"
    const val EDIT_ADDRESS_SNACKBAR_FLAG_KEY = "EDIT_ADDRESS_SNACKBAR_FLAG_KEY"

    //Custom Timing for snackbar
    const val SNACKBARD_DURATION = 2500
    const val SNACKBARD_TIMER_DURATION: Long = 3000

    // API Keys
    const val BS_KEY_USER_PAN_DETAILS = "userPanDetails"
    const val BS_KEY_CARD_DELIVERY_ADDRESS = "cardDeliveryAddress"
    const val BS_KEY_IS_FROM_CARD_BLOCK_REASON = "CardBlockReason"
    const val BS_KEY_IS_ONLINE_TRANSACTION_ON = "isOnlineTransactionOn"
    const val BS_KEY_IS_CARD_DELIVERED = "isCardDelivered"
    const val BS_KEY_IS_FROM_PFORILE_TO_BENEFICIARY = "isFromProfileToBeneficiaryListActivity"
    const val BS_KEY_CARD_SCREEN = "MainCardScreen"
    const val BS_KEY_IS_FROM_CHANGED_TRANSACTION_LIMIT_SCREEN =
        "isFromChangedTransactionLimitScreen"
    const val BS_KEY_OTHER_CARD_BLOCK_REASON = "OtherCardBlockReason"
    const val BS_KEY_CHANGE_TRANSACTION_LIMIT_SCREEN = "ChangeTransactionLimitScreen"
    const val BS_KEY_PAN_NUMBER = "panNumber"
    const val BS_KEY_ERROR_TYPE = "errorType"
    const val BS_KEY_IS_CARD_BLOCK = "isCardBlock"
    const val BS_KEY_IS_AADDRESS_CONFIRMED_BEFORE_CARD_BLOCK = "isAddressConfirmedBeforeCardBlock"
    const val BS_KEY_CARD_ACTIVE_STATUS = "CardActiveStatus"


    const val BS_KEY_PRIMARY_COLOR = "PrimaryColor"
    const val BS_KEY_PRIMARY_DARK_COLOR = "PrimaryDarkColor"
    const val BS_KEY_ACCENT_COLOR = "AccentColor"
    const val BS_KEY_EMAIL = "email"
    const val BS_KEY_EMPLOYEE_ID = "employeeId"
    const val EMAIL_ADDRESS = "Email address"
    const val BS_KEY_ALLOW = "allow"
    const val BS_KEY_CHANNEL = "channel"
    const val BS_KEY_PER_TRANSACTION = "perTransaction"
    const val BS_KEY_DAILY = "daily"
    const val BS_VALUE_ATM_CHANNEL = "ATM"
    const val BS_VALUE_SWIPE_CHANNEL = "POS"
    const val BS_VALUE_ONLINE_CHANNEL = "ECOM"
    const val BS_KEY_LOCATION = "location"
    const val BS_KEY_TRANSACTION_LIMIT_VALUES = "transactionLimitValues"

    //success message
    const val OTP_VERIFIED = "OTP_VERIFIED"
    const val OTP_SENT = "OTP_SENT"

    //WebView Title name
    const val HELP_TITLE = "Help"
    const val FAQS_TITLE = "FAQs"
    const val NOTIFICATIONS_TITLE = "Notifications"
    const val OFFERS_AND_DEALS_TITLE = "Offers & Deals"
    const val USER_PROFILE_FLAG = "UserFlag"
    const val USER_URL = "URL"
    const val TECHINICAL_ERROR_CODE = 500
    const val TECHINICAL_ERROR_CROSSED_CODE = 600
    const val INVALID_ACCESS_TOKEN = "Invalid accessToken "
    const val DEVICE_BINDING_FAILED = "DEVICE_BINDING_FAILED"
    const val EMP_NOT_VERIFIED = "Sorry, You are not eligible for AdvancePay"
    const val MOBILE_MISMATCH = "Sorry, Please enter your employer registered mobile number."
    const val MOBILE_MISMATCH_KEY = "MOBILE_MISMATCH"
    const val PAN_MISMATCH = "Sorry, Please enter correct PAN number"
    const val CARD_SET_PIN_REDIRECT_URL = "https://localhost:8081"


    //clevertap  User Profile Keys
    const val CL_USER_NAME = "Name"
    const val CL_USER_IDENTITY = "Identity"
    const val CL_USER_EMAIL = "Email"
    const val CL_USER_PHONE = "Phone"
    const val CL_USER_GENDER = "Gender"
    const val CL_USER_EMPLOYED = "Employed"
    const val CL_USER_EMPLOYEE_ID = "Employee Id"
    const val CL_USER_EDUCATION = "Education"
    const val CL_USER_DOB = "DOB"
    const val CL_USER_TIME_STAMP = "TimeStamp"
    const val CL_USER_ADDRESS = "Address"
    const val CL_USER_PHOTO = "Photo"

    // User Event Keys Name
    const val CL_IMEI_NUMBER = "IMEI"
    const val CL_SESSION = "Session"
    const val CL_USER_MOBILE_NUMBER = "Mobile Number"
    const val CL_USER_EVENT_ID = "Event ID"
    const val CL_USER_EVENT_NAME = "Event Name"
    const val CL_USER_EVENT_ITEM = "Item"
    const val CL_USER_EVENT_STATUS = "Status"
    const val CL_USER_EVENT_REASON = "Reason"
    const val CL_USER_EVENT_TYPE = "Type"
    const val CL_USER_EVENT_TRANSACTION_FILTER = "Transaction Filter"
    const val CL_USER_EVENT_ACCOUNT_TYPE_FILTER = "Account Type Filter"
    const val CL_USER_EVENT_TRANSACTION_ID = "Transaction ID"
    const val CL_USER_EVENT_TRANSACTION_STATUS = "Transaction Status"
    const val CL_USER_EVENT_TRANSACTION_AMOUNT = "Amount"
    const val CL_USER_EVENT_ACCOUNT_NUMBER = "Account Number"
    const val CL_USER_EVENT_ADVANCE_STATUS = "Advance Status"
    const val CL_USER_EVENT_AMOUNT_PAID = "Amount Paid"
    const val CL_USER_EVENT_TRANSACTION_CHARGES = "Transaction Charges"
    const val CL_USER_EVENT_RECEIVER_BANK_IFSCODE = "Receiver Bank IFSCode"

    // Clevertap Module Wise  Event Name
    const val CL_USER_EVENT_ADVANCE = "Advance Event"
    const val CL_USER_EVENT_PROFILE = "Profile Event"
    const val CL_USER_EVENT_MONEY_TRANSFER = "Money Transfer Event"
    const val CL_USER_EVENT_PASSBOOK = "Passbook Event"
    const val CL_USER_EVENT_CARD_MANAGEMENT = "Card Management Event"
    const val CL_USER_EVENT_HOME = "Home Event"
    const val CL_USER_EVENT_ONBOARDING = "OnBoarding Event"

    // Clevertap screen Wise  Event Name
    const val CL_USER_MOBILE_VERIFICATION = "Mobile Verified - New Number"
    const val CL_USER_RESEND_OTP = "Resend OTP"
    const val CL_USER_LOGIN_POST_MOBILE_VERIFICATION = "Login post mobile verification"
    const val CL_USER_FORGOT_PASSCODE = "Forgot Passcode from onBoarding"
    const val CL_USER_PAN_VERIFY = "PAN Verify"
    const val CL_USER_LOGIN_AFTER_RESET_PASSCODE = "Reset - Forgot Passcode - Onboarding"
    const val CL_USER_SET_PASSCODE = "Pin setting successfully"
    const val CL_USER_VERIFY_OTP = "Mobile verification successful - Existing User"
    const val CL_USER_KYC_SUCCESS = "User KYC success"
    const val CL_USER_KYC_FAILED = "KYC failed"
    const val CL_USER_AGREED_TERMS_CONDITION = "Agreed for Terms and Condition"
    const val CL_USER_ACCOUNT_OPENED = "Account Opened"
    const val CL_USER_ACCOUNT_OPENING_FAILED = "Account opening failed"
    const val CL_USER_EMPLOYMENT_CHECKING = "Employment checking failed"
    const val CL_USER_BACK_SET_PASSCODE = "Go back set passcode page"
    const val CL_USER_CLOSE_BADHAI_HO = "Close badhai ho page"
    const val CL_USER_BACK_CARD_DELIVERY_ADDRESS = "Go back card delivery address"
    const val CL_USER_BACK_PAN_EMPLOYEE = "Go back PAN & Employee page"
    const val CL_USER_BACK_RESET_PASSCODE = "Go back reset passcode page"
    const val CL_USER_BACK_VERIFY_PAN = "Go back verify PAN page"
    const val CL_USER_BACK_ENTER_PASSCODE = "Go back enter passcode page"
    const val CL_USER_BACK_OTP_VERIFY = "Go back OTP verify page"
    const val CL_USER_BACK_TERMS_CONDITION = "Go back terms & condition page"

    // Event name for user profile module
    const val CL_USER_PROFILE_PAGE_LOAD = "User Profile Page Load"
    const val CL_USER_PROFILE_PAGE_LOAD_ERROR = "User Profile Page Load - Error"
    const val CL_ACCESS_USER_DETAILS = "Access User details"
    const val CL_USER_CHANGE_EMAIL_SUCCESSFUL = "Change Email Successfull"
    const val CL_USER_CHANGE_ADDRESS = "Change Address"
    const val CL_USER_HELP = "Help & FAQs"
    const val CL_USER_LOGOUT = "Logout"
    const val CL_USER_FAQs = "View FAQs"
    const val CL_USER_RATES_CHARGES = "View Rates & Charges"
    const val CL_USER_MANAGE_PAYEES = "Manage Payees"
    const val CL_USER_PROFILE_EDIT_PAYEE_LIST = "Edit Payee List - Profile"
    const val CL_USER_PROFILE_delete_PAYEE_LIST = "Delete Payee List - Profile"
    const val CL_USER_MANAGE_PAYEES_GO_BACK_PROFILE = "Go Back - Payee List - Profile"
    const val CL_USER_DELETE_PAYEES_GO_BACK_MANAGE_PAYEE = "Go Back - Delete Payees Page - Profile"
    const val CL_USER_PASSCODE_RESET = "Passcode Reset Attempt"
    const val CL_USER_PASSCODE_FROM_PROFILE = "Forgot Passcode from Profile"
    const val CL_USER_VERIFY_PAN_FROM_PROFILE = "Verify PAN number from Profile"
    const val CL_USER_SHARE_ACCOUNT_DETAIL_PROFILE = "Share account details profile"
    const val CL_USER_RESET_PASSCODE_FROM_PROFILE = "Reset Passcode from profile"
    const val CL_USER_GO_BACK_HOME_PROFILE = "Go back home profile"
    const val CL_USER_GO_BACK_MY_DETAILS = "Go back my details"
    const val CL_USER_GO_BACK_ENTER_EMAIL = "Go back enter email"
    const val CL_USER_GO_BACK_ENTER_ADDRESS_PROFILE = "Go back enter address profile"
    const val CL_USER_GO_BACK_SAVE_ADDRESS_POPUP = "Go back - Save Address Pop up"

    // Event ID for user profile module
    const val CL_USER_PROFILE_PAGE_LOAD_EVENT_ID = "U1"
    const val CL_USER_PROFILE_PAGE_LOAD_ERROR_EVENT_ID = "U1N"
    const val CL_USER_ACCESS_USER_DETAILS_EVENT_ID = "U2"
    const val CL_USER_CHANGE_EMAIL_SUCCESSFULL_EVENT_ID = "U2I4"
    const val CL_USER_CHANGE_ADDRESS_EVENT_ID = "U2I5"
    const val CL_USER_HELP_EVENT_ID = "U3"
    const val CL_USER_VIEW_RATES_CHARGES_EVENT_ID = "U4"
    const val CL_USER_VIEW_FAQS_EVENT_ID = "U5"
    const val CL_USER_CHANGE_PASSCODE_PROFILE_EVENT_ID = "U7"
    const val CL_USER_FORGOT_PASSCODE_PROFILE_EVENT_ID = "U7FP"
    const val CL_USER_FORGOT_PASSCODE_TO_PASSCODE_PROFILE_EVENT_ID = "U7FPB"
    const val CL_USER_PAN_VERIFY_PASSCODE_RESET_PROFILE_EVENT_ID = "U7FPV"
    const val CL_USER_SHARE_ACCOUNT_DETAIL_PROFILE_EVENT_ID = "U9"
    const val CL_USER_PASSCODE_RESET_SUCCESS_PROFILE_EVENT_ID = "U8"
    const val CL_USER_LOGOUT_EVENT_ID = "U10"
    const val CL_USER_MANAGE_PAYEES_EVENT_ID = "U6"
    const val CL_USER_MANAGE_PAYEES_GO_BACK_PROFILE_EVENT_ID = "U6B1"
    const val CL_USER_DELETE_PAYEES_GO_BACK_MANAGE_PAYEE_EVENT_ID = "U6B2"
    const val CL_USER_EDIT_PAYEES_EVENT_ID = "U6I1"
    const val CL_USER_DELETE_PAYEES_EVENT_ID = "U6I2"
    const val CL_USER_GO_BACK_HOME_PROFILE_EVENT_ID = "U1B"
    const val CL_USER_GO_BACK_MY_DETAILS_EVENT_ID = "U2B"
    const val CL_USER_GO_BACK_ENTER_EMAIL_EVENT_ID = "U2I1B1"
    const val CL_USER_GO_BACK_ENTER_ADDRESS_PROFILE_EVENT_ID = "U2I5B1"
    const val CL_USER_GO_BACK_SAVE_ADDRESS_POPUP_EVENT_ID = "U2I5B2"


    // Event ID for user Home module
    const val CL_ADD_PAGE_ACCESS_EVENT_ID = "H1"
    const val CL_ADD_MONEY_HOME_EVENT_ID = "H9"
    const val CL_USER_ACCESS_MONEY_TRANSFER_EVENT_ID = "H5"
    const val CL_USER_ACCESS_PASSBOOK_EVENT_ID = "H6"
    const val CL_USER_ACCESSS_ADVANCE_PAGE_EVENT_ID = "H7"
    const val CL_USER_SEE_OFFER_DEALS_EVENT_ID = "H8"
    const val CL_USER_SHARE_ACCOUNT_DETAILS_HOME_EVENT_ID = "H9WS"
    const val CL_USER_CONFIRM_CARD_DELIVERY_EVENT_ID = "H10"
    const val CL_USER_CARD_NOT_DELIVERED_EVENT_ID = "H10N"
    const val CL_USER_CLOSE_ADD_MONEY_EVENT_ID = "H9B"
    const val CL_USER_CLOSE_ADVANCE_NOTIFICATION_EVENT_ID = "H3B"
    const val CL_USER_ACCESS_CARD_MANAGEMENT_EVENT_ID = "H4"
    const val CL_USER_LOAD_ADVANCE_NOTIFICATION_EVENT_ID = "H3"
    const val CL_USER_CLICK_ADVANCE_DUE_AMOUNT_EVENT_ID = "H3l1"
    const val CL_USER_SHOP_DEALS_EVENT_ID = "H8l1"
    const val CL_USER_CARD_NOT_DELIVERED_DELIVERED_EVENT_ID = "H12"
    const val CL_USER_RE_ORDER_CARD_EVENT_ID = "H13"
    const val CL_USER_ADD_NEW_ADDRESS_HOME_EVENT_ID = "H13NA"
    const val CL_USER_SAVE_NEW_ADDRESS_HOME_EVENT_ID = "H13NAS"
    const val CL_USER_SET_CARD_PIN_EVENT_ID = "H11"
    const val CL_USER_HELP_HOME_EVENT_ID = "H2"

    //  Event name for Home  module
    const val CL_ADD_PAGE_ACCESS = "Page Access"
    const val CL_ADD_MONEY_HOME = "Add Money Home"
    const val CL_USER_ACCESS_MONEY_TRANSFER = "Access Money Transfer"
    const val CL_USER_ACCESS_PASSBOOK = "Access Passbook"
    const val CL_USER_ACCESSS_ADVANCE_PAGE = "Access Advance Page"
    const val CL_USER_SEE_OFFER_DEALS = "See Offer & Deals"
    const val CL_USER_SHARE_ACCOUNT_DETAILS_HOME = "Share Account Details - Home"
    const val CL_USER_CONFIRM_CARD_DELIVERY = "Confirm Card Delivery"
    const val CL_USER_CARD_NOT_DELIVERED = "Card not delivered - Dispatched"
    const val CL_USER_CLOSE_ADD_MONEY = "Close Add Money"
    const val CL_USER_CLOSE_ADVANCE_NOTIFICATION = "Close Advance Notification"
    const val CL_USER_ACCESS_CARD_MANAGEMENT = "Access Card Management"
    const val CL_USER_LOAD_ADVANCE_NOTIFICATION = "Load Advance Notification"
    const val CL_USER_CLICK_ADVANCE_DUE_AMOUNT = "Click Advance Due Amount"
    const val CL_USER_SHOP_DEALS = "Shop Deals"
    const val CL_USER_CARD_NOT_DELIVERED_DELIVERED = "Card Not Delivered-Delivered"
    const val CL_USER_RE_ORDER_CARD = "Re-Order Card"
    const val CL_USER_ADD_NEW_ADDRESS_HOME = "Add New Address"
    const val CL_USER_SAVE_NEW_ADDRESS_HOME = "Save New Address"
    const val CL_USER_SET_CARD_PIN = "Set Card pin"
    const val CL_USER_HELP_HOME = "Help"

    // Event name for Card Management Module
    const val CL_USER_CHANGE_CARD_STATUS = "Change Card Status"
    const val CL_USER_BLOCK_CARD = "Block Card"
    const val CL_USER_CARD_BLOCK_REASON = "Card Block Reason"
    const val CL_USER_BLOCK_CARD_CANCELLED = "Refrain @ last step - Card Block"
    const val CL_USER_BLOCK_CARD_DIALOG_CLOSED = "Close Confirm Card Block"
    const val CL_USER_CARD_BLOCK_REASON_GO_BACK = "Go back - Reason to Block"
    const val CL_USER_CONFIRM_ADDRESS_TO_CARD_BLOCK_REASON_GO_BACK = "Go back - Confirm Address - Card Block"
    const val CL_USER_DELETE_ADDRESS_CARD_BLOCK = "Delete Address-Card Block"
    const val CL_USER_ADD_NEW_ADDRESS = "Add New Address-Card Block"
    const val CL_USER_ADD_NEW_ADDRESS_CARD_BLOCK_GO_BACK = "Go back - Add Address - Card Block"
    const val CL_USER_SAVE_NEW_ADDRESS = "Save New Address-Card Block"
    const val CL_USER_CHANGE_CARD_PIN = "Change Card Pin"
    const val CL_USER_TOGGLE_ONLINE_TRANSACTION = "Toggle Online Transactions"
    const val CL_USER_TOGGLE_ATM_WITHDRAWAL = "Toggle ATM Withdrawal"
    const val CL_USER_TOGGLE_CARD_SWIPE = "Toggle Card Swipe"
    const val CL_USER_VIEW_TRANSACTION_LIMITS = "View Transaction Limits"
    const val CL_USER_VIEW_TRANSACTION_LIMITS_GO_BACK = "Go back - View Txn Limits"
    const val CL_USER_EDOT_TRANSACTION_LIMITS_GO_BACK = "Go back - Edit Txn Limits"
    const val CL_USER_CHANGE_TRANASACTION_LIMIT_ATTEMPT = "Change Transaction Limit Attempt"
    const val CL_USER_CHANGE_AND_SAVE_TRANASACTION_LIMIT = "Attempt to Save Txn Limits Changes"
    const val CL_USER_RESET_FORGOT_PASSCODE_TRANSACTION_LIMIT =
        "Reset Forgot Passcode Transaction Limit"
    const val CL_USER_FORGOT_PASSCODE_TRANSACTION_LIMIT = "Forgot Passcode - Txn Limits"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_TRANSACTION_LIMIT_GO_BACK =
        "PAN Verify Forgot Passcode Transaction Limit - Go Back"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_TRANSACTION_LIMIT =
        "PAN Verify - FP - Txn Limits"
    const val CL_USER_FORGOT_PASSCODE_BLOCK_CARD = "Forgot Passcode Block Card"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_BLOCK_CARD =
        "PAN Verify Forgot Passcode Block Card"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_BLOCK_CARD_GO_BACK =
        "PAN Verify Forgot Passcode Block Card - GO Back"
    const val CL_USER_RESET_FORGOT_PASSCODE_BLOCK_CARD = "Reset Forgot Passcode Block Card"
    const val CL_USER_CARD_MANAGEMENT_PAGE_LOAD = "Card Management Page Load"
    const val CL_USER_CARD_MANAGEMENT_PAGE_ERROR = "Card Management Page Error"
    const val CL_USER_CARD_MANAGEMENT_GO_BACK_HOME = "Go back Home - Card Management"


    //clevertap Money Transfer Keys
    const val CL_MONEY_TRANSFER_PAGE_LOAD = "Money Transfer Page Load"
    const val CL_MONEY_TRANSFER_PAGE_ERROR = "Money Transfer Page Error"
    const val CL_PAYEE_LIST_MONEY_TRANSFER = "Payee List - Money Transfer"
    const val CL_EDIT_PAYEE_LIST_MONEY_TRANSFER = "Edit Payee List - Money Transfer"
    const val CL_DELETE_PAYEES_MONEY_TRANSFER = "Delete Payees - Money Transfer"
    const val CL_SELECT_PAYEE = "Select Payee"
    const val CL_ADD_RECEIVER_ACCOUNT_SUCCESSFULLY = "Add Receiver Account Successfully"
    const val CL_MONEY_TRANSFER_ATTEMPT = "Money Transfer Attempt"
    const val CL_ACCEPT_CHARGES = "Accept Charges"
    const val CL_CANCEL_TRANSFER_CHARGES = "Cancel transfer - Charges"
    const val CL_FORGOT_PASSCODE_MONEY_TRANSFER = "Forgot Passcode - Money Transfer"
    const val CL_FORGOT_PASSCODE_CHANGE_CARD_LIMITS = "Forgot Passcode - Change Card Limits"
    const val CL_PAN_VERIFY_FORGOT_PASSCODE_MONEY_TRANSFER =
        "PAN Verify - Forgot Passcode - Money Transfer"
    const val CL_RESET_FORGOT_PASSCODE_MONEY_TRANSFER = "Reset - Forgot Passcode - Money Transfer"
    const val CL_RESET_FORGOT_PASSCODE_CHANGE_CARD_LIMITS =
        "Reset - Forgot Passcode - Card change trsnaction limits"
    const val CL_MONEY_TRANSFER_EXECUTED = "Money Transfer Executed"
    const val CL_SHARE_ON_WHATSAPP_TXN_DETAILS_MONEY_TRANSFER =
        "Share on Whatsapp - Txn details - Money Transfer"
    const val CL_NEED_HELP = "Need Help"
    const val CL_GO_BACK_HOME_MONEY_TRANSFER = "Go back Home - Money Transfer"
    const val CL_GO_BACK_PAYEE_LIST_MONEY_TRANSFER = "Go Back - Payee List - Money Transfer"
    const val CL_GO_BACK_EDIT_PAYEES_PAGE_MONEY_TRANSFER =
        "Go Back - Edit Payees Page - Money Transfer"
    const val CL_GO_BACK_ENTER_PAYEE_DETAILS = "Go Back - Enter Payee Details"
    const val CL_GO_BACK_PAISE_BHEJO = "Go Back - Paise Bhejo"
    const val CL_GO_BACK_ENTER_PASSCODE_MONEY_TRANSFER = "Go Back - Enter Passcode - Money Transfer"
    const val CL_GO_BACK_PAN_VERIFY_FP_MONEY_TRANSFER = "Go Back - PAN Verify - FP - Money Transfer"
    const val CL_GO_BACK_RESET_FP_MONEY_TRANSFER = "Go Back - Reset - FP - Money Transfer"

    //EventID Money Transfer Keys
    const val CL_MONEY_TRANSFER_PAGE_LOAD_EVENT_ID = "M1"
    const val CL_MONEY_TRANSFER_PAGE_ERROR_EVENT_ID = "M1N"
    const val CL_PAYEE_LIST_MONEY_TRANSFER_EVENT_ID = "M2"
    const val CL_EDIT_PAYEE_LIST_MONEY_TRANSFER_EVENT_ID = "M2I1"
    const val CL_DELETE_PAYEES_MONEY_TRANSFER_EVENT_ID = "M2I2"
    const val CL_SELECT_PAYEE_EVENT_ID = "M3"
    const val CL_ADD_RECEIVER_ACCOUNT_SUCCESSFULLY_EVENT_ID = "M4"
    const val CL_MONEY_TRANSFER_ATTEMPT_EVENT_ID = "M5"
    const val CL_ACCEPT_CHARGES_EVENT_ID = "M5I1"
    const val CL_CANCEL_TRANSFER_CHARGES_EVENT_ID = "M5I1N"
    const val CL_FORGOT_PASSCODE_MONEY_TRANSFER_EVENT_ID = "M5FP"
    const val CL_PAN_VERIFY_FORGOT_PASSCODE_MONEY_TRANSFER_EVENT_ID = "M5FPP"
    const val CL_RESET_FORGOT_PASSCODE_MONEY_TRANSFER_EVENT_ID = "M5FPR"
    const val CL_MONEY_TRANSFER_EXECUTED_EVENT_ID = "M6"
    const val CL_SHARE_ON_WHATSAPP_TXN_DETAILS_MONEY_TRANSFER_EVENT_ID = "M6SW"
    const val CL_NEED_HELP_EVENT_ID = "M6I1"
    const val CL_GO_BACK_HOME_MONEY_TRANSFER_EVENT_ID = "M1B"
    const val CL_GO_BACK_PAYEE_LIST_MONEY_TRANSFER_EVENT_ID = "M2B1"
    const val CL_GO_BACK_EDIT_PAYEES_PAGE_MONEY_TRANSFER_EVENT_ID = "M2B2"
    const val CL_GO_BACK_ENTER_PAYEE_DETAILS_EVENT_ID = "M4B"
    const val CL_GO_BACK_PAISE_BHEJO_EVENT_ID = "M5B1"
    const val CL_GO_BACK_ENTER_PASSCODE_MONEY_TRANSFER_EVENT_ID = "M5B2"
    const val CL_GO_BACK_PAN_VERIFY_FP_MONEY_TRANSFER_EVENT_ID = "M5FPB1"
    const val CL_GO_BACK_RESET_FP_MONEY_TRANSFER_EVENT_ID = "M5FPB2"

    // EventID name for Card Management Module
    const val CL_USER_CARD_MANAGEMENT_PAGE_LOAD_EVENT_ID = "C1"
    const val CL_USER_CARD_MANAGEMENT_PAGE_ERROR_EVENT_ID = "C1N"
    const val CL_USER_CARD_MANAGEMENT_GO_BACK_HOME_EVENT_ID = "C1B"
    const val CL_USER_CHANGE_CARD_STATUS_EVENT_ID = "C2"
    const val CL_USER_BLOCK_CARD_EVENT_ID = "C3"
    const val CL_USER_BLOCK_CARD_CANCELLED_EVENT_ID = "C3I4"
    const val CL_USER_BLOCK_CARD_DIALOG_CLOSED_EVENT_ID = "C3B4"
    const val CL_USER_CARD_BLOCK_REASON_EVENT_ID = "C3I1"
    const val CL_USER_CARD_BLOCK_REASON_GO_BACK_EVENT_ID = "C3B1"
    const val CL_USER_CONFIRM_ADDRESS_TO_CARD_BLOCK_REASON_GO_BACK_EVENT_ID = "C3B2"
    const val CL_USER_DELETE_ADDRESS_CARD_BLOCK_EVENT_ID = "C3I2"
    const val CL_USER_SAVE_NEW_ADDRESS_EVENT_ID = "C3AAS"
    const val CL_USER_CHANGE_CARD_PIN_EVENT_ID = "C4"
    const val CL_USER_ADD_NEW_ADDRESS_CARD_BLOCK_EVENT_ID = "C3AA"
    const val CL_USER_ADD_NEW_ADDRESS_CARD_BLOCK_GO_BACK_EVENT_ID = "C3AAB"
    const val CL_USER_TOGGLE_ONLINE_TRANSACTION_EVENT_ID = "C5"
    const val CL_USER_TOGGLE_ATM_WITHDRAWAL_EVENT_ID = "C6"
    const val CL_USER_TOGGLE_CARD_SWIPE_EVENT_ID = "C7"
    const val CL_USER_VIEW_TRANSACTION_LIMITS_EVENT_ID = "C8"
    const val CL_USER_VIEW_TRANSACTION_LIMITS_GO_BACK_EVENT_ID = "C8B1"
    const val CL_USER_EDIT_TRANSACTION_LIMITS_GO_BACK_EVENT_ID = "C8B2"
    const val CL_USER_CHANGE_TRANASACTION_LIMIT_ATTEMPT_EVENT_ID = "C8I1"
    const val CL_USER_CHANGE_AND_SAVE_TRANASACTION_LIMIT_EVENT_ID = "C8I2"
    const val CL_USER_RESET_FORGOT_PASSCODE_TRANSACTION_LIMIT_EVENT_ID = "C8FPR"
    const val CL_USER_FORGOT_PASSCODE_TRANSACTION_LIMIT_EVENT_ID = "C8FP"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_TRANSACTION_LIMIT_EVENT_ID = "C8FPP"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_TRANSACTION_LIMIT_GO_BACK_EVENT_ID = "C8FPPB1"
    const val CL_USER_FORGOT_PASSCODE_BLOCK_CARD_EVENT_ID = "C3FP"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_BLOCK_CARD_EVENT_ID = "C3FPP"
    const val CL_USER_PAN_VERIFY_FORGOT_PASSCODE_BLOCK_CARD_GO_BACK_EVENT_ID = "C3FPPB1"
    const val CL_USER_RESET_FORGOT_PASSCODE_BLOCK_CARD_EVENT_ID = "C3FPR"


    //Passbook module Event name
    const val CL_PASSBOOK_PAGE_LOAD = "Passbook Page Load"
    const val CL_PASSBOOK_PASSBOOK_PAGE_ERROR = "Passbook Page Error"
    const val CL_PASSBOOK_VIEW_ADVANCE_INFO = "View Advance Info"
    const val CL_PASSBOOK_ACCESS_MONEY_TRANSFER = "Access Money Transfer"
    const val CL_PASSBOOK_TIME_FILTER_TXNS = "Time Filter Txns"
    const val CL_PASSBOOK_CUSTOM_FILTER_TXNS = "Custom Filter Txns"
    const val CL_PASSBOOK_VIEW_TXN_STATUS_AND_INFO = "View Txn Status & Info"
    const val CL_PASSBOOK_HELP_TXN_PASSBOOK = "Help - Txn - Passbook"
    const val CL_PASSBOOK_GO_BACT_HOME_PASSBOOK = "Go bact Home - Passbook"


    //Passbook module Event ID
    const val CL_PASSBOOK_PAGE_LOAD_EVENT_ID = "P1"
    const val CL_PASSBOOK_PASSBOOK_PAGE_ERROR_EVENT_ID = "P1N"
    const val CL_PASSBOOK_VIEW_ADVANCE_INFO_EVENT_ID = "P2"
    const val CL_PASSBOOK_ACCESS_MONEY_TRANSFER_EVENT_ID = "P3"
    const val CL_PASSBOOK_TIME_FILTER_TXNS_EVENT_ID = "P4"
    const val CL_PASSBOOK_CUSTOM_FILTER_TXNS_EVENT_ID = "P5"
    const val CL_PASSBOOK_VIEW_TXN_STATUS_AND_INFO_EVENT_ID = "P6"
    const val CL_PASSBOOK_HELP_TXN_PASSBOOK_EVENT_ID = "P6I1"
    const val CL_PASSBOOK_GO_BACT_HOME_PASSBOOK_EVENT_ID = "P1B"

    //Clevertap event ID
    var CL_USER_NOT_VERIFIED = "0"
    var CL_USER_PASSCODE_VARIABLE_LOGIC = "0"
    var CL_USER_FORGOT_PASSCODE_TEXT_CLICK = "0"
    var CL_USER_VERIFY_PAN_BUTTON_CLICK = "0"
    var CL_USER_RESET_PASSCODE_BUTTON_CLICK = "0"
    var CL_USER_RESET_PASSCODE_PROFILE_CLICK = "0"

    const val CL_USER_MOBILE_VERIFICATION_EVENT_ID = "O4"
    const val CL_USER_RESEND_OTP_VERIFICATION_EVENT_ID = "O4l1"
    const val CL_USER_EXISTING_USER_LOGIN_EVENT_ID = "O5I1"
    const val CL_USER_ONBOARDING_FORGOT_PASSCODE_EVENT_ID = "O5FP"
    const val CL_USER_PAN_VERIFICATION_EVENT_ID = "O5FPP"
    const val CL_USER_RESET_PASSCODE_EVENT_ID = "O5FPR"
    const val CL_USER_OTP_VERIFICATION_EVENT_ID = "O5"
    const val CL_USER_SET_PASSCODE_EVENT_ID = "O9"
    const val CL_USER_KYC_SUCCESS_EVENT_ID = "O6"
    const val CL_USER_EMPLOYMENT_CHECKING_EVENT_ID = "O6N1"
    const val CL_USER_KYC_FAILED_EVENT_ID = "O6N2"
    const val CL_USER_KARZA_VERIFICATION_FAILED_EVENT_ID = "O6N3"
    const val CL_USER_AGREED_TERMS_CONDITION_EVENT_ID = "O7"
    const val CL_USER_ACCOUNT_OPENED_EVENT_ID = "O8"
    const val CL_USER_ACCOUNT_OPENING_FAILED_EVENT_ID = "O8N"
    const val CL_USER_BACK_TERMS_CONDITION_EVENT_ID = "O7B"

    const val CL_USER_BACK_SET_PASSCODE_EVENT_ID = "O9B"
    const val CL_USER_CLOSE_BADHAI_HO_EVENT_ID = "O8C"
    const val CL_USER_BACK_CARD_DELIVERY_ADDRESS_EVENT_ID = "O6B3"
    const val CL_USER_BACK_PAN_EMPLOYEE_EVENT_ID = "O6B2"
    const val CL_USER_BACK_KYC_HOME_EVENT_ID = "O6B1"
    const val CL_USER_BACK_RESET_PASSCODE_EVENT_ID = "O5FPB2"
    const val CL_USER_BACK_VERIFY_PAN_EVENT_ID = "O5FPB1"
    const val CL_USER_BACK_ENTER_PASSCODE_EVENT_ID = "O5B1"
    const val CL_USER_BACK_OTP_VERIFY_EVENT_ID = "O4B1"

    // Clevertap Dummy data
    const val CL_USER_PROFILE_PHOTO =
        "https://i.pinimg.com/originals/ea/6c/93/ea6c931c623881ecd29955db118c7742.png"
    const val CL_USER_DUMMY_NAME = "ABC"
    const val CL_USER_DUMMY_EMAIL = "abc@gmail.com"

    //Clevertap Advance module Event name
    const val CL_ADVANCE_PAGE_LOAD = "Advance Page Load"
    const val CL_GO_BACK_TO_HOME_FROM_ADVANCE = "Go back Home - Advance"
    const val CL_ADVANCE_PAGE_ERROR = "Advance Page Error"
    const val CL_ADVANCE_TXN_DETAILS = "See Advance Txn Details"
    const val CL_GO_BACK_TO_ADVANCE_FROM_TXN_DETAILS = "Go back - See Advance Txn Details"
    const val CL_ADVANCE_ADD_AMOUNT_TO_UNLOCK = "Add Amount to Unlock"
    const val CL_ADVANCE_SHARE_BANK_DETAILS = "Share Bank Details - Advance"

    //Clevertap Advance event ID
    var CL_ADVANCE_PAGE_LOAD_EVENT_ID = "A1"
    var CL_GO_BACK_TO_HOME_FROM_ADVANCE_EVENT_ID = "A1B"
    var CL_ADVANCE_PAGE_ERROR_EVENT_ID = "A1N"
    var CL_ADVANCE_TXN_DETAILS_EVENT_ID = "A4"
    var CL_GO_BACK_TO_ADVANCE_FROM_TXN_DETAILS_EVENT_ID = "A4B"
    var CL_ADVANCE_ADD_AMOUNT_TO_UNLOCK_EVENT_ID = "A5"
    var CL_ADVANCE_SHARE_BANK_DETAILS_EVENT_ID = "A5SW"

    // error messages
    const val FETCHING_LOCATION_MESSAGE = "We are fetching your location. Kindly wait."

    //card screen
    const val CARD_NOT_DELIVERED_INACTIVE_MSG =
        "Card deliver hone se pehele aap ATM cash withdrawals or card swipe activate nahi kr sakte."
    const val CARD_NOT_DELIVERED_FOR_BLOCK_MSG =
        "Card deliver hone se pehele aap card block nahi kr sakte."
    const val CARD_NOT_DELIVERED_FOR_CHANGE_PIN_MSG =
        "Card deliver hone se pehele aap card ka pin change nahi kr sakte."
    const val CARD_INACTIVE_FOR_PAYMENT_MODES_MSG =
        "Payment mode active krne k lie kripya apna card phir se active kijiye"
    const val CARD_INACTIVE_STATUS_MSG = "Apne apna card temporarily band kr diya hai."
    const val CARD_ACTIVE_STATUS_MSG = "Apne apna card on kr diya hai."
    const val ONLINE_TRANSACTION_INACTIVE_MSG = "Apne online transactions band kr di hai."
    const val ONLINE_TRANSACTION_ACTIVE_MSG = "Apne online transactions on kr di hai."
    const val ATM_INACTIVE_MSG = "Apne ATM transactions band kr di hai."
    const val ATM_ACTIVE_MSG = "Apne ATM transactions on kr di hai."
    const val SWIPE_INACTIVE_MSG = "Apne Card Swipe transactions band kr di hai."
    const val SWIPE_ACTIVE_MSG = "Apne Card Swipe transactions on kr di hai."
    const val CARD_BLOCKED_SUCCESS_MSG = "Apka card block ho gya hai."
    const val CARD_BLOCKED_FAILURE_MSG = "Apka card block nahi ho paya hai."
    const val CARD_UNBLOCKED_SUCCESS_MSG = "Apka card unblock ho gya hai."
    const val TRANSACTION_LIMIT_CHANGED_SUCCESS_MSG = "Apki transaction limit change ho chuki hai."
    const val TRANSACTION_LIMIT_CHANGED_FAILURE_MSG =
        "Apki transaction limits change nahi hui hai. Kripya firse try kariye."
    const val CARD_PIN_CHANGED_SUCCESS_MSG = "Apka card pin change ho chuka hai."
    const val CARD_PIN_CHANGED_FAILURE_MSG = "Apka card pin change nhi huya hai."
    const val CARD_INACTIVE_BEFORE_DELIVERY_MSG =
        "Card deliver hone se pehele aap ATM cash withdrawals or card swipe activate nahi kr sakte."
}